version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "ğŸ¤– "
    groups:
      eslint:
        patterns:
          - "eslint*"
      remix:
        patterns:
          - "@remix-run/*"
      stylelint:
        patterns:
          - "stylelint*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "ğŸ¤– "
